"""add confidence to dishes

Revision ID: 966220475452
Revises: 
Create Date: 2026-02-09 12:57:23.034767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '966220475452'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_dishes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confidence', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_dishes', schema=None) as batch_op:
        batch_op.drop_column('confidence')

    # ### end Alembic commands ###
